apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kubeconeu-knative-func
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/thomasvitale/kubeconeu-knative-func:latest
          ports:
            - containerPort: 8080
